### ISSUE TITLE
Consider adding aniwey's game YWMI 

### ISSUE THREAD

**Issue by jeremyredhead** [candybox2/candybox2.github.io#1]
This isn't quite the right repository for this issue, but I'm not really sure where else to ask about this :P

If you didn't already know, "You Won't Make It" is another game made by aniwey (GPL-licensed) that disappeared when they took their site down. It's a fun game, and I think it deserves proper preservation as well.

Also, if you don't want deal with scraping it from the Web Archive, I would gladly handle that.

**Comment by kvaps** [comment]
I think this question to @aniwei

**Comment by jeremyredhead** [comment]
I'm sorry, could you clarify? I don't quite understand what you mean by that.
(BTW, I don't believe that aniwey is on Github)

**Comment by kvaps** [comment]
I hoped to receive any feedback from @aniwei, unfortunately summon is failed :)
If you want to upload this project here, I don't see any problem for yo do this.
I can create repo for you, and give you rights if you want, this project will be accessed by https://candybox2.github.io/you-wont-make-it/ link. OK?

**Comment by jeremyredhead** [comment]
Sounds good! 👍

**Comment by kvaps** [comment]
@jeremyredhead, done, I sent you invation
