### ISSUE TITLE
Application cache removed in Chrome 85

### ISSUE THREAD

**Issue by Ciferlingvulo** [candybox2/candybox2.github.io#25]
Hello,
I have been playing Candybox 2 for a few weeks. Today I updated my browser and I noticed that suddenly Browser Save stopped working. I see the following message :

> Your browser does not seem to support HTML5. (local storage and application cache)
> You should update your browser in order to use the local saving feature.

I checked the code and realized the issue was that the following returned false : ```"applicationCache" in window && window.applicationCache !== null```
(code from [here](https://github.com/candybox2/candybox2.github.io/blob/d7dcea3d579d078cb4fd3b6d03cd7a31841ef23d/code/main/LocalSaving.ts#L72))

After some research I learnt that it was actually disabled on purpose on the latest version of Chrome (85) : https://developers.google.com/web/updates/2020/07/chrome-85-deps-rems

Could you please update the code to make Browser Save work again ?

Thanks in advance ! :)

**Comment by DileSoft** [comment]
#27

**Comment by kvaps** [comment]
fixed by https://github.com/candybox2/candybox2.github.io/pull/27
