### ISSUE TITLE
Visualising issue

### ISSUE THREAD

**Issue by SsmikK** [candybox2/candybox2.github.io#30]
![Screenshot_25](https://user-images.githubusercontent.com/51160144/132950591-de93c64a-52a8-46a2-99a3-221dc0858348.png)
So I have this issue entering the page. Same thing happens with map, houses and everything. I was trying to fix it myself but didn't work 
![Screenshot_26](https://user-images.githubusercontent.com/51160144/132950603-825efa03-5ca9-41fc-9a99-32c5a74db2f5.png)
![Screenshot_27](https://user-images.githubusercontent.com/51160144/132950646-50aa8cb5-0a9b-40db-99e7-165c37c9a406.png)

**Comment by NekoAlosama** [comment]
It's an issue with the text font. The whole game is displayed by text. For some reason, the monospaced font (the kind of font where all of the characters are of an equal size) isn't loading for you. Instead, it's loading a normal font.


Example:
In a normal font: 
"wwwww"
"lllll"
The first is longer than the second, even though they are both 5 characters long.

In a monospaced font: 
`wwwww`
`lllll`
They are both the same length now.

**Comment by SsmikK** [comment]
> It's an issue with the text font. The whole game is displayed by text. For some reason, the monospaced font (the kind of font where all of the characters are of an equal size) isn't loading for you. Instead, it's loading a normal font.
> 
> Example:
> In a normal font:
> "wwwww"
> "lllll"
> The first is longer than the second, even though they are both 5 characters long.
> 
> In a monospaced font:
> `wwwww`
> `lllll`
> They should both look like same length now, unless it's not loading for you.

I totally do understand that. Apparently, it works good with some fonts, but it looks bad for me. I'd like to know what fonts do you and other people use in it

**Comment by NekoAlosama** [comment]
What browser are you using to play this? It should work fine for desktop browsers, as all the main ones should have support for using multiple fonts depending on the page, having a monospaced font for pages that ask for it. Check your browser settings to see if there's options for fonts, and either look for the monospaced font option or change your default font temporarily.

**Comment by SsmikK** [comment]
I am using google chrome and I resolved this issue with placing the "Consolas" font
